server:
  port: 8989
  servlet:
    jsp:
      init-parameters:
        development: true

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/recommend
    url: jdbc:mysql://localhost:3306/dharma?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: liu
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB


mybatis:
  mapper-locations: classpath*:com/peng/mapper/*.xml
  type-aliases-package: com.peng.entity

logging:
  level:
    root: info
    com.peng.dao: debug